### ISSUE TITLE
The demo 'obj_loading' have bug,obj file can't be load success

### ISSUE THREAD

**Issue by rhettli** [gen2brain/raylib-go#130] opened 2021-03-06 09:58 UTC
![Screenshot 2021-03-06 175541](https://user-images.githubusercontent.com/26317003/110202701-68547080-7ea5-11eb-866f-0c8aa86f4430.png)

**Comment by rhettli** [comment] 2021-03-06 10:16
it be tested at master branch,i test all demo ,just got one error.

**Comment by rhettli** [comment] 2021-03-06 10:36
And by the way,raylib-go not support write unicode string, why?

**Comment by gen2brain** [comment] 2021-03-14 11:41
This issue is a duplicate of #72

**Comment by gen2brain** [comment] 2021-05-26 11:28
This is now fixed. Just use `rl.SetMaterialTexture` like in examples.

**Closed by gen2brain** 2021-05-26 11:28 UTC
