### ISSUE TITLE
IsKeyPressed / IsKeyReleased Sending False Values

### ISSUE THREAD

**Issue by SolarLune** [gen2brain/raylib-go#13] opened 2017-09-17 17:42 UTC
Hello!

So basically, IsKeyPressed() and IsKeyReleased() seem to be sending false values if you hold the key down for about a second or longer. Here's a quick example:

```go

package main

import (
	"github.com/gen2brain/raylib-go/raylib"
)

func main() {

	raylib.SetConfigFlags(raylib.FlagWindowResizable)
	raylib.InitWindow(640, 480, "Test Game")
	raylib.SetTargetFPS(30)

	for !raylib.WindowShouldClose() {

		// Update

		if raylib.IsKeyPressed(raylib.KeyA) {
			println("A pressed")
		}
		if raylib.IsKeyReleased(raylib.KeyB) {
			println("B released")
		}

		// Draw

		raylib.BeginDrawing()

		raylib.ClearBackground(raylib.Black)

		raylib.DrawFPS(10, 10)

		raylib.EndDrawing()

	}

}

```

If you tap the A key, "A pressed" will be printed to the console (which is fine). If you press and hold it, and then release the key after about a second, "A pressed" will be printed to the console twice. A similar thing for the B key - tapping "B" will print "B released" to the console, but pressing, holding for about a second, and releasing the B key will print "B released" twice.

I'm running Solus 3 (Linux) 64-bit.

**Comment by raysan5** [comment] 2017-09-17 19:07
Just tested it in the C version of the library and it works fine, maybe it's related to Go binding...

**Comment by gen2brain** [comment] 2017-09-18 07:26
I just tried in Go and I cannot reproduce it. Works as expected for me.

**Comment by SolarLune** [comment] 2017-09-18 17:18
Dang, that's not good. I'm running Go 1.9, as well, so it's not a version issue. Not sure what it could be.

**Comment by SolarLune** [comment] 2017-09-18 17:24
I notice that it seems like it might be tied to the framerate (and perhaps also to how often keyboard events are updated)? At higher framerates (like >= 120), I can't reproduce it, while at typical framerates (30, 60), it's easy to reproduce.

**Comment by raysan5** [comment] 2017-09-18 20:24
Could you try in another computer and another keyboard?

**Comment by gen2brain** [comment] 2017-10-27 18:10
@SolarLune There were some changes in library. Can you update and try now?

**Comment by gen2brain** [comment] 2017-12-05 19:53
I will close this one, please file a new issue if you still have problems.

**Closed by gen2brain** 2017-12-05 19:53 UTC
