### ISSUE TITLE
cubicmap example doesn't work

### ISSUE THREAD

**Issue by makeworld-the-better-one** [gen2brain/raylib-go#131] opened 2021-03-13 19:13 UTC
I tried to run [this](https://github.com/gen2brain/raylib-go/tree/master/examples/models/cubicmap) example on my Linux machine, and this was the output on the screen (it was rotating as it should):

![Screenshot_2021-03-13_14-07-02](https://user-images.githubusercontent.com/25111343/111041338-c0d7c080-8405-11eb-9b8f-b75d688550a3.png)

I was expecting something like this, which is taken from the official [examples page](https://www.raylib.com/examples.html):

![image](https://user-images.githubusercontent.com/25111343/111041365-d8af4480-8405-11eb-8ed4-63afe9cd20f2.png)

Here is the command line log:

```
INFO: Initializing raylib 3.1-dev
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Render size:  800 x 450
INFO:     > Screen size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) UHD Graphics 620 (KBL GT2)
INFO:     > Version:  4.6 (Core Profile) Mesa 20.3.4
INFO:     > GLSL:     4.60
INFO: GL: Supported extensions count: 223
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: FILEIO: [cubicmap.png] File loaded successfully
INFO: IMAGE: [cubicmap.png] Data loaded successfully (32x16)
INFO: TEXTURE: [ID 3] Texture created successfully (32x16 - 1 mipmaps)
INFO: VAO: [ID 2] Mesh uploaded successfully to VRAM (GPU)
{VertexCount:8244 TriangleCount:2748 Vertices:0x312cc00 Texcoords:0x315d100 Texcoords2:<nil> Normals:0x3144e80 Tangents:<nil> Colors:<nil> Indices:<nil> AnimVertices:<nil> AnimNormals:<nil> BoneIds:<nil> BoneWeights:<nil> VaoID:2 VboID:0x308d1c0}
INFO: FILEIO: [cubicmap_atlas.png] File loaded successfully
INFO: IMAGE: [cubicmap_atlas.png] Data loaded successfully (256x256)
INFO: TEXTURE: [ID 4] Texture created successfully (256x256 - 1 mipmaps)
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: TEXTURE: [ID 3] Unloaded texture data from VRAM (GPU)
INFO: TEXTURE: [ID 4] Unloaded texture data from VRAM (GPU)
INFO: VAO: [ID 2] Unloaded vertex data from VRAM (GPU)
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xfffffffffffffff9 pc=0x7f32d382fc69]

runtime stack:
runtime.throw(0x5b9c02, 0x2a)
	/usr/lib/go/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
	/usr/lib/go/src/runtime/signal_unix.go:718 +0x2e5

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4e0f10, 0xc0000c5a18, 0x29)
	/usr/lib/go/src/runtime/cgocall.go:154 +0x5b fp=0xc0000c5960 sp=0xc0000c5928 pc=0x42cefb
github.com/gen2brain/raylib-go/raylib._Cfunc_UnloadModel(0x3f800000, 0x0, 0x3f80000000000000, 0x0, 0x0, 0x3f800000, 0x0, 0x3f80000000000000, 0x1, 0x308e650, ...)
	_cgo_gotypes.go:5091 +0x51 fp=0xc0000c5a18 sp=0xc0000c5960 pc=0x4c6cf1
github.com/gen2brain/raylib-go/raylib.UnloadModel.func1(0xc0000c5bc0)
	/home/makeworld/go/pkg/mod/github.com/gen2brain/raylib-go@v0.0.0-20210227124741-9d258bad6516/raylib/models.go:195 +0xda fp=0xc0000c5ba8 sp=0xc0000c5a18 pc=0x4c7a7a
github.com/gen2brain/raylib-go/raylib.UnloadModel(0x3f800000, 0x0, 0x3f80000000000000, 0x0, 0x0, 0x3f800000, 0x0, 0x3f80000000000000, 0x1, 0x308e650, ...)
	/home/makeworld/go/pkg/mod/github.com/gen2brain/raylib-go@v0.0.0-20210227124741-9d258bad6516/raylib/models.go:195 +0x2b fp=0xc0000c5bc0 sp=0xc0000c5ba8 pc=0x4c712b
main.main()
	/home/makeworld/go/src/github.com/makeworld-the-better-one/raylib-sandbox/main.go:73 +0x798 fp=0xc0000c5f88 sp=0xc0000c5bc0 pc=0x4c9b78
runtime.main()
	/usr/lib/go/src/runtime/proc.go:225 +0x256 fp=0xc0000c5fe0 sp=0xc0000c5f88 pc=0x45f3f6
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000c5fe8 sp=0xc0000c5fe0 pc=0x48e8c1

```

Note the panic at the end is unrelated, and a separate issue. It only happens with I close the window.

```
➤ go version
go version go1.16 linux/amd64
```

I have installed raylib-go from the latest commit: 9d258bad6516. But I also tested with the `3.1-dev` and `3.0.0` tags, and got the exact same error.

Also, it would be nice if the [first person maze](https://github.com/raysan5/raylib/blob/3.0.0/examples/models/models_first_person_maze.c) example was included. Is that possible with raylib-go?

**Comment by chunqian** [comment] 2021-03-14 06:26
@makeworld-the-better-one 
I know what was wrong with this project, so I created [go-raylib](https://github.com/chunqian/go-raylib) and now it supports linux, I tested it on xubuntu 16.04 and it works fine, you can try it.

**Comment by makeworld-the-better-one** [comment] 2021-03-14 06:46
Can confirm. Thanks!!

**Comment by gen2brain** [comment] 2021-03-14 11:41
This issue is a duplicate of #72

**Closed** 2021-05-26 11:28 UTC
