### ISSUE TITLE
Some functions not available in GO

### ISSUE THREAD

**Issue by nicholassimon** [gen2brain/raylib-go#76] opened 2019-06-11 05:06 UTC
Hi, just wondering some functions in the Cheatsheet do not seem to be available in Golang, ie. DrawTextRecEx as well as others. Are the GO bindings not up to date and is there any way these will be updated?

**Comment by gen2brain** [comment] 2019-06-12 11:51
Duplicate of #77

**Closed by gen2brain** 2019-06-12 11:51 UTC
